name: Release
on:
    push:
        tags: ['*']
env:
    GITHUB_TAG: ${{ github.ref }}
jobs:
    tests:
        name: Test
        uses: inkapplications/.github/.github/workflows/kmp-checks.yml@1.0.3
    verify-docs:
        runs-on: ubuntu-latest
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2.3.4
            -
                name: Docs Requirements
                run: >
                    ./gradlew dokkaHtmlMultiModule -Pversion=latest &&
                    if [[ $(git status --porcelain) ]]; then
                        echo "Docs are out of date!" && exit 1;
                    else
                        echo "Docs are current" && exit 0;
                    fi
    publish:
        name: Publish to Maven Central
        needs: tests
        secrets: inherit
        uses: inkapplications/.github/.github/workflows/kmp-maven-publish.yml@1.0.3
        with:
            version: ${{ github.ref_name }}
            publish-linux-arm64: false
            publish-android-native-arm32: false
            publish-android-native-arm64: false
            publish-android-native-x86: false
            publish-android-native-x64: false
            publish-ios-simulator-arm64: false
            publish-watchos-simulator-arm64: false
            publish-watchos-arm32: false
            publish-tvos-simulator-arm64: false
            publish-watchos-device-arm64: false
    draft-release:
        name: Draft Github Release
        needs: [publish]
        runs-on: ubuntu-latest
        steps:
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1.1.4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref_name }}
                  draft: true
                  prerelease: false
                  body: "See CHANGELOG.md for details"
